- paths:
    INSTALLATION_PATH: '.local/share/molex'
- metadata:
    DELIMITERS:
        ALBUM_TITLE:
            - ';'
        SONG_TITLE:
            - ';'
        ARTIST:
            - ';'
            - '/'
        SPLIT_EXCEPTIONS:
            - 'K/DA'
            - 'AU/RA'
    PROCESS_ARTIST_ROLES: True

